name: Container deployment ca-toolit-imggal-001

# When this action will be executed
on: 
  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CATOOLITIMGGAL001_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CATOOLITIMGGAL001_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CATOOLITIMGGAL001_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: sagarpandey88.dockerhub.io
          registryUsername: ${{ secrets.CATOOLITIMGGAL001_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CATOOLITIMGGAL001_REGISTRY_PASSWORD }}
          containerAppName: ca-toolit-imggal-001
          resourceGroup: rg-toolit-imggal
          imageToBuild: ${{ secrets.CATOOLITIMGGAL001_REGISTRY_USERNAME }}/toolit-imagegallery:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


